### ISSUE TITLE
char(1) Field Returns Extra Spaces When Using NONE Character Set in fbdb

### ISSUE THREAD

**Issue by cwangfr** [hipercompl/fbdb#5]
# Issue Description: 
char(1) field reads as 4 bytes when using NONE character set

# Description:

While developing with fbdb, I encountered a bug where my database uses the NONE character set. I have a field defined as char(1), but on the Flutter side, it is read as a 4-byte string. For example, when the field content is 'Y', the Flutter side gets the result string 'Y ' (with three extra spaces after 'Y').

# Steps to Reproduce:

Create a table with a char(1) field.
Insert a value into that field, e.g., 'Y'.
Read the value of that field in Flutter.
Observe that the value read is 'Y ' instead of the expected 'Y'.
Expected Behavior:

The char(1) field should return a single character 'Y' when read, without any extra padding spaces.

# Actual Behavior:

The char(1) field returns 'Y ', which includes three extra spaces.

# Additional Information:

Database character set: NONE
Flutter version: 3.22.2
fbdb version: 1.1.1
FireBirdSQL version: 2.5.9

**Comment by ttyrakow** [comment]
The client character set in fbdb is always set to UTF-8 (Dart code uses Unicode internally and there are built-in routines to convert to and from UTF-8, unlike other encodings). And I think you encountered this Firebird behavior:

[https://stackoverflow.com/questions/54657441/when-use-charset-parameter-pdo-fetchs-blank-spaces-in-fields#54672762](https://stackoverflow.com/questions/54657441/when-use-charset-parameter-pdo-fetchs-blank-spaces-in-fields#54672762). 

I will try to compensate for it by right-trimming the extra spaces to the length calculated as (bytes received / 4), where 4 is the number of bytes per one Unicode character.
Note, that this behavior concerns only CHAR columns (not VARCHAR) and is intrinsic to Firebird client library, so I can probably work around it, but I'm not able to eliminate the actual cause.
I'll try to update the code asap (possibly this weekend) and publish an update. Will let you know in the comment when it's ready.

**Comment by ttyrakow** [comment]
The issue should be fixed in vesion 1.1.2, which has just been uploaded to pub.dev to be published.

**Comment by ttyrakow** [comment]
Fixed, added more tests to prevent regressions.
